<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Xsd.aspx.cs" Inherits="wstester.Xsd" %>
<%@ Import Namespace="System.Linq" %>
<%@ Import Namespace="System.Xml" %>
<%@ Import Namespace="System.Net" %>
<%@ Import Namespace="System.IO" %>
<%@ Import Namespace="System.Xml.Schema" %>
<%@ Import Namespace="wstester" %>
<%@ Import Namespace="System.Collections.Generic" %>
<script runat="server">

	protected void Page_Load(object sender, EventArgs e)
	{
		if (!IsPostBack && Request["element"] != null)
		{
			var element = Element.Deserialize(Request["element"]);
			XsdTextBox.Text = element.xsd;
			XsdButton_Click(null, null);
			TreeView1.CollapseAll();
			var selected_node = TreeView1.FindNode(element.TreeViewPath);
			if (selected_node != null)
			{
				var tmp_node = selected_node;
				while (tmp_node.Parent != null)
				{
					tmp_node.Parent.Expand();
					tmp_node = tmp_node.Parent;
				}
				selected_node.Parent.Expand();
				selected_node.Select();
			}
		}
		Form.DefaultButton = "XsdButton";
	}

	protected void DelUrlsButton_Click(object sender, EventArgs e)
	{
		File.Delete(Server.MapPath("~/App_Data/XsdList.json"));
	}

	protected void XsdButton_Click(object sender, EventArgs e)
	{
		IDictionary<string, XmlDocument> xsd_;
		XmlNamespaceManager nsmgr;
		if (!XsdTextBox.Text.Equals(Session["xsd-url"]))
		{
			xsd_ = LoadXsd(XsdTextBox.Text, out nsmgr);

			XmlSchemaSet xss = LoadCompileSchemas(xsd_.Values, nsmgr);

			AddXsdUrlToJsonAutocompleteStorage(Server.MapPath("~/App_Data/XsdList.json"), XsdTextBox.Text);

			Session["xsd-url"] = XsdTextBox.Text;
			Session["xsd-xsd"] = xsd_;
			Session["xsd-nsmgr"] = nsmgr;
			Session["xsd-xss"] = xss;
		}
		else
		{
			xsd_ = (IDictionary<string, XmlDocument>)Session["xsd-xsd"];
			nsmgr = (XmlNamespaceManager)Session["xsd-nsmgr"];
		}

		BuildServiceTreeView(TreeView1, xsd_, nsmgr);
	}

	//protected void TreeView1_TreeNodeDataBound(object sender, TreeNodeEventArgs e)
	//{

	//}

	//protected void TreeView1_TreeNodePopulate(object sender, TreeNodeEventArgs e)
	//{

	//}

	//protected void TreeView1_DataBinding(object sender, EventArgs e)
	//{

	//}

	//protected void TreeView1_DataBound(object sender, EventArgs e)
	//{

	//}
</script>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
	<title>XSD</title>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
	<link type="text/css" rel="Stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/redmond/jquery-ui.css" />
	<style type="text/css">
		body
		{
			font-family: Arial;
			font-size: 10pt;
		}
		.heading1 
		{
			color: #ffffff; 
			font-family: Tahoma; 
			font-size: 26px; 
			font-weight: normal; 
			background-color: #003366; 
			margin-top: 10px; 
			margin-bottom: 0px; 
			/*margin-left: -30px;*/
			padding-top: 10px; 
			padding-bottom: 3px; 
			padding-left: 15px; 
			/*width: 105%;*/
		}
		/*ul { margin-top: 10px; margin-left: 20px; }
		ol { margin-top: 10px; margin-left: 20px; }*/
		li { margin-top: 10px; color: #000000; }
		.link-button-class { white-space: nowrap; text-decoration: none; }
		.ui-autocomplete { font-size: 1em; }
	</style>
</head>
<body>
	<form id="form1" runat="server">
	<div>
		<table cellpadding="0" cellspacing="0" width="100%"><tr><td nowrap="nowrap" valign="top" style="padding-top:4px;">
		XSD URL:&nbsp;&nbsp;<br />
		<asp:LinkButton ID="DelUrlsButton" runat="server" onclick="DelUrlsButton_Click" CssClass="link-button-class" style="font-size:7pt;font-style:italic;">Clear URL hints</asp:LinkButton>
		</td><td style="width:100%;" valign="top">
		<nobr><asp:TextBox ID="XsdTextBox" runat="server" Width="570px"></asp:TextBox>&nbsp;&nbsp;</nobr>
		<asp:Button ID="XsdButton" runat="server" onclick="XsdButton_Click" CssClass="link-button-class" Text="Get XSD" />
		</td></tr></table>
		<hr />
		<asp:TreeView ID="TreeView1" runat="server" ImageSet="Arrows" >
			<ParentNodeStyle Font-Bold="False" />
			<LevelStyles>
				<asp:TreeNodeStyle Font-Underline="False" ForeColor="Black" />
				<asp:TreeNodeStyle Font-Underline="False" ForeColor="Black" />
				<asp:TreeNodeStyle Font-Underline="False" />
				<asp:TreeNodeStyle Font-Underline="False" ForeColor="Black" CssClass="TreeViewDesc" />
			</LevelStyles>
			<%--<HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />--%>
			<SelectedNodeStyle Font-Bold="true"
				HorizontalPadding="0px" VerticalPadding="0px" /><%-- Font-Underline="True" ForeColor="#5555DD"--%>
			<NodeStyle Font-Names="Tahoma" Font-Size="10pt" 
				HorizontalPadding="5px" NodeSpacing="0px" VerticalPadding="0px" /><%-- ForeColor="Black"--%>
		</asp:TreeView>
		<%-- DataSourceID="XmlDataSource1" 
			AutoGenerateDataBindings="True" ondatabinding="TreeView1_DataBinding" 
			ondatabound="TreeView1_DataBound" 
			ontreenodedatabound="TreeView1_TreeNodeDataBound" 
			ontreenodepopulate="TreeView1_TreeNodePopulate" EnableViewState="False">
			<DataBindings>
				<asp:TreeNodeBinding DataMember="wsdl:definitions" TextField="targetNamespace" />
				<asp:TreeNodeBinding DataMember="wsdl:service" TextField="name" />
				<asp:TreeNodeBinding DataMember="wsdl:port" TextField="name" />
			</DataBindings>
		</asp:TreeView>
		<asp:XmlDataSource ID="XmlDataSource1" runat="server"><data><root /></data></asp:XmlDataSource>--%>
		
		<div id="result" runat="server"></div>
		<pre id="pre_result" runat="server"></pre>
	</div>
	</form>
</body>
<script type="text/javascript">
	(function ($) {
		$('#<% = TreeView1.ClientID %> a').has('img').attr('hideFocus', 'hidefocus');
		$('#<% = TreeView1.ClientID %> a:first').focus();
		$('a.TreeViewDesc').css({ 'white-space': 'normal', 'font-style': 'italic', 'font-size': '8pt' })
			.wrap('<div style="width: 400px;"></' + 'div>');
		var _$xsd_inp_ = $('#<% = XsdTextBox.ClientID %>'), _xsd_val_;
		_$xsd_inp_.autocomplete({
			source: 'Urls.ashx?filename=XsdList.json',
			select: function (event, ui) {
				_$xsd_inp_.val(ui.item.value);
				if (_xsd_val_ !== ui.item.value)
					<%= ClientScript.GetPostBackEventReference(XsdButton, "", false) %>;
			}
		}).focus(function () {
			_xsd_val_ = this.value;
			this.select();
		});
	})(jQuery);
</script>
</html>
